apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: db6
  description: CEDA's Postgres Cluster System
spec:
  owner: user:default/asharwood
  domain: domain:default/ceda-systems
  type: service

---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: db6
  description: CEDA Postgres Cluster Instance
spec:
  type: service
  owner: user:default/asharwood
  lifecycle: production